"""
etl.py – Export filtered cases to RDF (Turtle) using a simplified CDM ontology
and (optionally) upload them to AllegroGraph (or another SPARQL triple store).
"""

import pandas as pd
import requests
from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, XSD

# ---------------------------------------------------------
# RDF NAMESPACES
# ---------------------------------------------------------

# Base namespace for resources generated by this system
BASE = Namespace("https://fieldlab1.example.org/resource/")

# CDM (Common Data Model) namespace for ontology terms
CDM = Namespace("https://fieldlab1.example.org/cdm/")


def dataframe_to_rdf(df: pd.DataFrame) -> bytes:
    """
    Convert a filtered cases DataFrame to an RDF graph.

    Models:
      - Incident nodes (cdm:Incident)
      - Location nodes (cdm:Location)
    and links them with cdm:hasLocation.

    Input:
        df: pandas DataFrame with at least columns:
            - ID
            - Country
            - Region
            - Camp
            - Event date
            - Event type
            - Affected status
            - Affected number
            - Sensitive (Yes/No)
            - Anonymous (Yes/No)

    Output:
        RDF graph serialized as Turtle, returned as bytes.
    """
    g = Graph()
    g.bind("cdm", CDM)
    g.bind("res", BASE)

    for _, row in df.iterrows():
        case_id = str(row["ID"])
        incident_uri = BASE[f"incident/{case_id}"]

        # Declare the incident
        g.add((incident_uri, RDF.type, CDM.Incident))

        # ---- BASIC INCIDENT PROPERTIES ----

        # Event date
        event_date_val = row.get("Event date")
        if pd.notna(event_date_val):
            g.add(
                (
                    incident_uri,
                    CDM.eventDate,
                    Literal(event_date_val, datatype=XSD.date),
                )
            )

        # Event type
        event_type_val = row.get("Event type")
        if pd.notna(event_type_val):
            g.add(
                (
                    incident_uri,
                    CDM.eventType,
                    Literal(str(event_type_val)),
                )
            )

        # Affected status
        aff_status_val = row.get("Affected status")
        if pd.notna(aff_status_val):
            g.add(
                (
                    incident_uri,
                    CDM.affectedStatus,
                    Literal(str(aff_status_val)),
                )
            )

        # Affected number
        aff_num_val = row.get("Affected number")
        if pd.notna(aff_num_val):
            try:
                aff_num_int = int(aff_num_val)
                g.add(
                    (
                        incident_uri,
                        CDM.affectedNumber,
                        Literal(aff_num_int, datatype=XSD.integer),
                    )
                )
            except (ValueError, TypeError):
                # If conversion fails, store as plain string
                g.add(
                    (
                        incident_uri,
                        CDM.affectedNumber,
                        Literal(str(aff_num_val)),
                    )
                )

        # Sensitive + Anonymous flags (as booleans)
        sens_val = row.get("Sensitive")
        if pd.notna(sens_val):
            is_sens = True if sens_val == "Yes" else False
            g.add(
                (
                    incident_uri,
                    CDM.isSensitive,
                    Literal(is_sens, datatype=XSD.boolean),
                )
            )

        anon_val = row.get("Anonymous")
        if pd.notna(anon_val):
            is_anon = True if anon_val == "Yes" else False
            g.add(
                (
                    incident_uri,
                    CDM.isAnonymous,
                    Literal(is_anon, datatype=XSD.boolean),
                )
            )

        # ---- LOCATION NODE ----
        country = row.get("Country")
        region = row.get("Region")
        camp = row.get("Camp")

        # Only make a location node if we have at least a country
        if pd.notna(country):
            # Build a simple, stable location ID
            def norm(x):
                return str(x).strip().lower().replace(" ", "-")

            loc_id_parts = [norm(country)]
            if pd.notna(region):
                loc_id_parts.append(norm(region))
            if pd.notna(camp):
                loc_id_parts.append(norm(camp))

            loc_id = "-".join(loc_id_parts)
            location_uri = BASE[f"location/{loc_id}"]

            # Link incident -> location
            g.add((incident_uri, CDM.hasLocation, location_uri))

            # Declare the location resource
            g.add((location_uri, RDF.type, CDM.Location))

            # Add country/region/camp literals to the location
            g.add((location_uri, CDM.country, Literal(str(country))))
            if pd.notna(region):
                g.add((location_uri, CDM.region, Literal(str(region))))
            if pd.notna(camp):
                g.add((location_uri, CDM.camp, Literal(str(camp))))

    return g.serialize(format="turtle").encode("utf-8")


# ---------------------------------------------------------
# AllegroGraph (or any SPARQL triple store) upload helper
# ---------------------------------------------------------

# ⚠️ CHANGE THESE VALUES to your real AllegroGraph server & repo
AG_SERVER_URL = "https://ag14402pptsl6sx7.allegrograph.cloud"      # e.g. "http://your-server:10035"
AG_REPOSITORY = "fieldlab1"                   # repository / catalog name
AG_USERNAME = "admin"                          # provided by your professor
AG_PASSWORD = "AksLESfmIoPOdhM4Xkc4ts"                          # provided by your professor


# Convenience constant for querying
SPARQL_ENDPOINT = f"{AG_SERVER_URL}/repositories/{AG_REPOSITORY}/sparql"



def upload_to_allegrograph(rdf_turtle: bytes):
    """
    Upload Turtle data to AllegroGraph.

    Input:
        rdf_turtle: bytes containing RDF in Turtle format.

    Returns:
        (success: bool, message: str, url: Optional[str])

        - success: True if HTTP status 2xx
        - message: human-readable description
        - url: the repository URL where data was uploaded (for FAIR/FDP registration)
    """
    # Endpoint where RDF statements are added
    endpoint = f"{AG_SERVER_URL}/repositories/{AG_REPOSITORY}/statements"
    repo_url = f"{AG_SERVER_URL}/repositories/{AG_REPOSITORY}"

    headers = {"Content-Type": "text/turtle"}

    try:
        resp = requests.post(
            endpoint,
            data=rdf_turtle,
            headers=headers,
            auth=(AG_USERNAME, AG_PASSWORD),
            timeout=30,
        )
    except Exception as e:
        return False, f"Upload failed: {e}", None

    if 200 <= resp.status_code < 300:
        return True, "RDF uploaded successfully to AllegroGraph.", repo_url
    else:
        return (
            False,
            f"Upload failed with status {resp.status_code}: {resp.text}",
            None,
        )
